baseURL: 'http://localhost:1313/'
languageCode: 'en-us'
title: 'Hugo Profile'
theme: hugo-profile

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  page:
    - 'HTML'
    - 'RSS'

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: 'Lucas Anselmo Portfolio'
  description: Text about my cool site
  favicon: '/fav.png'
  useBootstrapCDN: false
  mathjax: false
  animate: true

  theme:
    defaultTheme: 'light'

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: 'Lucas Anselmo' # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: 'Lucas Anselmo.'
    subtitle: 'I build web applications.'
    content: 'A passionate front-end web software developer. I tend to make use of modern web technologies to create websites that look great, look great, respect web accessibility rules and function correctly.'
    image: /images/profile-picture.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: 'Resume'
      url: /file/CV_Lucas_Anselmo.pdf
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/lucas-anselmo-moraes-da-silva-543636161/
        - icon: fab fa-github
          url: https://github.com/LucasAnselmoSilva12345/
        - icon: fab fa-x-twitter
          url: https://twitter.com/LucasAnselmo202
  # About
  about:
    enable: true
    title: 'About Me'
    image: '/images/min-profile-picture.png'
    content: |-
      I would like to introduce myself as a Junior Front-end software development enthusiast with a passion for creating innovative digital experiences. I have a degree in Computer Science and bring with me a professional trajectory marked by valuable experiences and a solid commitment to quality and innovation.

      I started my professional journey in a project called “Training and Production of Teaching Material for Programming Competition Marathons”. This opportunity allowed me to build and apply materials that prepared teams for national and international programming competitions, highlighting my commitment to quality and education in the area.

      Later, I entered the world of website, software and application development, focusing on Front-end. As a web software development intern, I worked with software such as Open Journal System, Open Preprint System and Open Monograph Press. During this period, I focused on creating visual identities and themes for academic portals, in addition to developing personalized functionalities to meet the specific needs of each client.

      I highlight my competence in JavaScript and TypeScript languages, combined with frameworks such as React and Next.js. I developed and implemented widely used projects of my own, focusing on the extensive implementation of unit and integration tests, following agile methodologies and testing methodologies. Furthermore, all of my projects follow the digital accessibility guidelines defined by W3C, ensuring inclusive and accessible experiences for all users.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - 'React'
        - 'Next.js'
        - 'TypeScript'
        - 'JavaScript'
        - 'Jest'
        - 'React Testing Library'

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: 'Intern in Web Software Development'
        company: 'Lepidus Tecnologia'
        companyUrl: 'https://lepidus.com.br/'
        date: 'Aug 2021 - Aug 2023'
        content: 'I interned at Lepidus Tecnologia, working on the “Journals in the Cloud” project, creating portals and journals for Brazilian and Angolan institutions. Using open-source tools like OJS, OPS, and OMP, I crafted their visual identities, collaborating closely with clients to meet design preferences. Employing Figma for prototyping and Vue, CSS, HTML, and Smarty Template, I built themes, ensuring strict adherence to software documentation and conducting end-to-end tests with Cypress. I also implemented new functionalities, like a filtering plugin, following Test-Driven Development using PHP (Laravel), JavaScript (jQuery), Vue, HTML, CSS, PHPUnity, and Cypress. Resolving text display issues in journals, I applied a CSS fix using “font-display: swap” for seamless user experience. Additionally, I spearheaded the creation of Lepidus Tecnologias’ new corporate website, revamping its visual identity and technologies with Hugo, gaining WordPress expertise for site maintenance and contributing to internal functionalities like continuous integration (CI/CD) processes through YML in a Docker environment.'

      - job: 'Fellow – Project “Training and Production of Didactic Material for Programming Competition Marathons”'
        company: 'IFSP - Campus Salto'
        companyUrl: 'https://slt.ifsp.edu.br/'
        date: 'Jul 2020 - Jan 2021'
        content:
          In charge of developing the teaching material used in training the institute's competition team. This
          involves creating detailed, instructive content to ensure effective team preparation.
          Responsible for creating the material, providing training for the campus team, preparing members
          for several programming marathons throughout the academic year.
          I carried out a case study focused on “Dynamic Programming”, following the guidelines of the
          teacher responsible for the project. This required an in-depth analysis of this topic and detailed
          documentation of the results obtained.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: 'Bachelor of Science in Computer Science'
        school:
          name: 'Instituto Federal de Educação, Ciência e Tecnologia de São Paulo, Campus Salto'
          url: 'https://slt.ifsp.edu.br/'
        date: '2020 - 2023'
        content: |-
          I Published one paper in the Conict - Scientific Conference.
          - [Web Software and Application Assessment Tool for Accessibility Features People with Visual Impairments](https://ocs.ifsp.edu.br/conict/xivconict/paper/view/9702)
      - title: 'High School - Technician in Informatics'
        school:
          name: 'ETEC - Martinho Di Ciero'
          url: 'https://www.etecitu.com.br/'
        date: '2017 - 2019'

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: 'https://github.com/gurusabarish/hugo-profile'
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - 'Hugo'
          - 'Bootstrap'
          - 'Javascript'
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - 'Django'
          - 'Bootstrap'
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - 'Hugo'
          - 'Bootstrap'
          - 'Javascript'
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: lucasanselmodasilva02@gmail.com
    btnName: Mail me

  footer:
    socialNetworks:
      linkedin: https://www.linkedin.com/in/lucas-anselmo-moraes-da-silva-543636161/
      github: https://github.com/LucasAnselmoSilva12345/
      twitter: https://twitter.com/LucasAnselmo202

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: 'min read'
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: 'Read'
    toc: 'Table Of Contents'
    copyright: 'All rights reserved'
    pageNotFound: 'Page not found'
    emailText: 'Check out this site'

  datesFormat:
    article: 'Jan 2, 2006'
    articleList: 'Jan 2, 2006'
    articleRecent: 'Jan 2, 2006'

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
